server:
  port: 8081

spring:
  application:
    name: dr--r--r--
  main:
    allow-bean-definition-overriding: true
  profiles:
    activate:
      on-profile: local
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    consumer:
      bootstrap-servers: localhost:9093
    producer:
      bootstrap-servers: localhost:9093
  docker:
    compose:
      file: classpath:docker/docker-compose.yaml
      #서버가 켜지면 컨테이너들이 켜지고 꺼지면 알아서 꺼지나 필요할 때만 주석 제거
      lifecycle-management: start_only
  mail:
    host: smtp.gmail.com
    port: 587
    username: drxxrxxrxx@gmail.com
    password: eqtl dpnc kydw okkp
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:tcp://localhost/~/testdb
    username: sa
    password:
    hikari:
      connection-timeout: 300000
  jpa:
    hibernate:
      #애플리케이션 로딩 시점에 다 드랍하고 다시 생성
      ddl-auto: update
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        use_sql_comments: true
  batch:
    jdbc:
      initialize-schema: ALWAYS
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: classpath:security-storage-api/social/github/github.pub
            client-secret: classpath:security-storage-api/social/github/github.key
          kakao:
            client-id: classpath:security-storage-api/social/kakao/kakao.pub
            redirect-uri: http://localhost:8081/login/oauth/kakao
            client-authentication-method: POST
            client-secret: classpath:security-storage-api/social/kakao/kakao.key
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
              - gender
              - birthday
            client_name: kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
jwt:
  private.key: classpath:security-storage-api/jwt/jwt.key
  public.key: classpath:security-storage-api/jwt/jwt.pub
management:
  endpoints:
    web:
      exposure:
        include: "prometheus"

