server:
  port: 8081

spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    activate:
      on-profile: local
  data:
    redis:
      host: localhost
      port: 6379
  docker:
    compose:
      file: classpath:docker/docker-compose.yaml
      #서버가 켜지면 컨테이너들이 켜지고 꺼지면 알아서 꺼지나 필요할 때만 주석 제거
      #lifecycle-management: start_and_stop

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:mysql://localhost:3306/BATCH_SAMPLE?rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    hikari:
      connection-timeout: 300000

  jpa:
    hibernate:
      #애플리케이션 로딩 시점에 다 드랍하고 다시 생성
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        use_sql_comments: true
  batch:
    jdbc:
      initialize-schema: ALWAYS
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: e756d60c6372cbaf3a99
            client-secret: 5393f0d241b969b2aa13ea610fb89f8b4d4b2532
          kakao:
            client-id: d2ef8a5cdacf8c8485096cbc2628c907
            redirect-uri: http://localhost:8080/login/oauth/kakao
            client-authentication-method: POST
            client-secret: vhHlIzCEwLqTdJwpiyhwxaXOVYPfOjT6
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
              - gender
              - birthday
            client_name: kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDES
    pool-size: 2
    string-output-type: base64
    key-obtention-iterations: 100000
  secret-key:
    file-location: classpath:security-storage-api/jasypt.key
jwt:
  private.key: classpath:security-storage-api/jwt.key
  public.key: classpath:security-storage-api/jwt.pub
