version: '3.8'
networks:
  replica:
    driver: bridge

services:
  redis:
    container_name: redis
    image: redis:6.2
    ports:
      - 6379:6379
    networks:
      - replica
    volumes:
      - ./conf:/usr/local/etc/redis/
      # Redis 서버를 실행할 때 사용되는 명령어입니다. 이 명령어는 Redis 서버를 구동하고 지정된 경로의 Redis 설정 파일(redis.conf)을 사용하여 구성
    command: bash -c "apt-get update && apt-get install vim -y && redis-server /usr/local/etc/redis/redis.conf"
    restart: always
#    deploy:
#      resources:
#        limits:
#          memory: 512M
  redis-insight:
    image: redislabs/redisinsight:latest
    ports:
      - 8001:8001
  zookeeper:
    image: confluentinc/cp-zookeeper
    networks:
      - replica
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
    ports:
      - "2181:2181"

  kafka1:
    image: confluentinc/cp-kafka
    ports:
      - "9093:9093"
    networks:
      - replica
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9093
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#    deploy:
#      resources:
#        limits:
#          memory: 512M

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins_cicd
    volumes:
      - ./var/run/docker.sock:/var/run/docker.sock
      - ./jenkins:/var/jenkins_home
    ports:
      - "9090:8080"
    networks:
      - replica
    privileged: true
    user: root
#    deploy:
#      resources:
#        limits:
#          memory: 512M